- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{item}}"
      state: present

  - name: list of packages
    ansible.builtin.package:
      name:
        - git
        - mysql
        - postfix
        - nginx

