- name: insatall and run nginx package
  hosts: web
  become: yes

  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start and enabled nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
      