- name: insatall and run nginx package
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: run nginx
    ansible.builtin.services:
      name: nginx
      state: started
      